import cv2
import numpy as np

#################### X-Y CONVENTIONS #########################
# 0,0  X  > > > > >
#
#  Y
#
#  v  This is the image. Y increases downwards, X increases rightwards
#  v  Please return bounding boxes as ((xmin, ymin), (xmax, ymax))
#  v
#  v
#  v
###############################################################


def image_print(img):
    """
    Helper function to print out images, for debugging. Pass them in as a list.
    Press any key to continue.
    """
    cv2.imshow("image", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


def cd_color_segmentation(img, template):
    """
    Implement the cone detection using color segmentation algorithm
    Input:
        img: np.3darray; the input image with a cone to be detected. BGR.
        template: Not required, but can optionally be used to automate setting hue filter values.
    Return:
        bbox: ((x1, y1), (x2, y2)); the bounding box of the cone, unit in px
            (x1, y1) is the top left of the bbox and (x2, y2) is the bottom right of the bbox
    """
    ########## YOUR CODE STARTS HERE ##########

    # Step 1: Convert BGR to HSV
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    # Step 2: Create a binary mask for orange pixels

    # used hsv histogram generated by analyze_hsv for values
    lower_orange = np.array([0, 200, 80])
    upper_orange = np.array([30, 255, 255])
    mask = cv2.inRange(hsv, lower_orange, upper_orange)

    # Step 3: Morphological opening
    # Erosion removes small isolated noise pixels that passed the color filter.
    # Dilation then restores the cone's true area and fills holes from specular highlights.
    kernel = np.ones((5, 5), np.uint8)
    mask = cv2.erode(mask, kernel, iterations=1)
    mask = cv2.dilate(mask, kernel, iterations=2)

    # Step 4: Find external contours in the cleaned binary mask
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Step 5: If no orange regions found, return a zero-area bbox
    if not contours:
        return ((0, 0), (0, 0))

    # Step 6: Filter out contours that are too horizontally wide to be a cone.
    # From the debug images, wooden tables/shelves pass the color filter but
    # produce very wide, flat bounding boxes (width >> height).
    # A cone is roughly as wide as it is tall
    # We keep contours with width <= 2.5 * height; fall back to all if none pass
    cone_candidates = [c for c in contours
                       if cv2.boundingRect(c)[2] <= 2.5 * cv2.boundingRect(c)[3]]
    if not cone_candidates:
        cone_candidates = contours  # don't discard everything

    # Step 7: Among shape-filtered candidates, pick the largest by area
    largest = max(cone_candidates, key=cv2.contourArea)

    # Step 8: Compute axis-aligned bounding rect and convert to required format
    x, y, w, h = cv2.boundingRect(largest)
    bounding_box = ((x, y), (x + w, y + h))

    ########### YOUR CODE ENDS HERE ###########

    # Return bounding box
    return bounding_box


def cd_color_segmentation_line(img):
    """
    Detect orange line/tape on the ground.
    Input:  img: BGR image (may already be masked with annular ROI)
    Return: bbox: ((x1,y1),(x2,y2)) bounding box of detected line segment, or None
    """
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    lower_orange = np.array([0, 100, 80])
    upper_orange = np.array([30, 255, 255])
    mask = cv2.inRange(hsv, lower_orange, upper_orange)

    kernel = np.ones((5, 5), np.uint8)
    mask = cv2.erode(mask, kernel, iterations=1)
    mask = cv2.dilate(mask, kernel, iterations=2)

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        return None

    largest = max(contours, key=cv2.contourArea)
    x, y, w, h = cv2.boundingRect(largest)
    return ((x, y), (x + w, y + h))
